function q1dd = AccelerationJoint1(I1,I2,T2,g0,l1,lc1,lc2,m1,m2,q1,q2,q1d,q2d)
%ACCELERATIONJOINT1
%    Q1DD = ACCELERATIONJOINT1(I1,I2,T2,G0,L1,LC1,LC2,M1,M2,Q1,Q2,Q1D,Q2D)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Mar-2017 12:04:44

t2 = l1.^2;
t3 = lc2.^2;
t4 = lc1.^2;
t5 = m2.^2;
t6 = sin(q2);
t7 = cos(q1);
t8 = q2.*2.0;
t9 = q1d.^2;
t10 = q2d.^2;
q1dd = (I2.*T2.*-2.0-T2.*m2.*t3.*2.0+t2.*t3.*t5.*t9.*sin(t8)-I2.*g0.*l1.*m2.*t7.*2.0-I2.*g0.*lc1.*m1.*t7.*2.0-g0.*l1.*t3.*t5.*t7+g0.*l1.*t3.*t5.*cos(q1+t8)-T2.*l1.*lc2.*m2.*cos(q2).*2.0+l1.*lc2.*t3.*t5.*t6.*t9.*2.0+l1.*lc2.*t3.*t5.*t6.*t10.*2.0+I2.*l1.*lc2.*m2.*t6.*t9.*2.0+I2.*l1.*lc2.*m2.*t6.*t10.*2.0-g0.*lc1.*m1.*m2.*t3.*t7.*2.0+I2.*l1.*lc2.*m2.*q1d.*q2d.*t6.*4.0+l1.*lc2.*q1d.*q2d.*t3.*t5.*t6.*4.0)./(I1.*I2.*2.0+I1.*m2.*t3.*2.0+I2.*m2.*t2.*2.0+I2.*m1.*t4.*2.0+t2.*t3.*t5+m1.*m2.*t3.*t4.*2.0-t2.*t3.*t5.*cos(t8));
