function Tc1 = ComputeTorque1(I1,I2,g0,kd1,kp1,l1,lc1,lc2,m1,m2,q1,q2,q1d,q2d,qdes)
%COMPUTETORQUE1
%    TC1 = COMPUTETORQUE1(I1,I2,G0,KD1,KP1,L1,LC1,LC2,M1,M2,Q1,Q2,Q1D,Q2D,QDES)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    02-Mar-2017 12:08:36

t2 = lc2.^2;
t3 = m2.*t2;
t4 = cos(q2);
t5 = l1.*lc2.*m2.*t4;
t6 = I2+t3;
t7 = q1+q2;
t8 = cos(t7);
t9 = I2+t3+t5;
t10 = 1.0./t9;
t11 = sin(q2);
Tc1 = -(kd1.*q1d+kp1.*(q1-qdes)).*(I2+t3+t5-t6.*t10.*(I1+I2+m2.*(t2+l1.^2)+lc1.^2.*m1+l1.*lc2.*m2.*t4.*2.0))+g0.*lc2.*m2.*t8-g0.*t6.*t10.*(cos(q1).*(l1.*m2+lc1.*m1)+lc2.*m2.*t8)+l1.*lc2.*m2.*q1d.^2.*t11+l1.*lc2.*m2.*t6.*t10.*t11.*(q1d.*q2d.*2.0+q2d.^2);
