function eqn1 = ComputeAccel1(q1,q2,q1d,q2d)
%COMPUTEACCEL1
%    EQN1 = COMPUTEACCEL1(Q1,Q2,Q1D,Q2D)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    02-Mar-2017 10:49:28

t2 = q2.*2.0;
t3 = sin(q2);
t4 = q1d.^2;
eqn1 = -(cos(q1+t2).*9.81e2-cos(q1).*1.3734e4+t3.*t4.*5.0e2+q2d.^2.*t3.*5.0e2+t4.*sin(t2).*1.0e2+q1d.*q2d.*t3.*1.0e3)./(cos(t2).*1.0e2-1.35e3);
