function out1 = ComputeAccel2(q1,q2,q1d,q2d)
%COMPUTEACCEL2
%    OUT1 = COMPUTEACCEL2(Q1,Q2,Q1D,Q2D)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    28-Feb-2017 23:35:24

t2 = sin(q2);
out1 = (cos(q1+q2).*(-9.81e2./5.0e1)-cos(q1).*5.886e1+q2d.^2.*t2.*2.0+q1d.*q2d.*t2.*4.0)./(cos(q2).*2.0+5.0);
