function out1 = ComputeAccel1(q1,q2,q1d,q2d,qdes)
%COMPUTEACCEL1
%    OUT1 = COMPUTEACCEL1(Q1,Q2,Q1D,Q2D,QDES)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    28-Feb-2017 23:16:24

t2 = cos(q2);
t3 = t2.^2;
t4 = sin(q2);
t5 = q1+q2;
t6 = cos(t5);
t7 = q1d.^2;
out1 = 1.0./(t2.*2.0+5.0).^2.*(q1.*1.0875e5+q1d.*4.64e4-qdes.*1.0875e5-t6.*1.962e4-cos(q1).*7.3575e4-q1.*t3.*1.5e4-q1d.*t3.*6.4e3+qdes.*t3.*1.5e4+t2.*t6.*1.962e3+t4.*t7.*5.0e2+q2d.^2.*t4.*2.5e3+q1d.*q2d.*t4.*5.0e3+t2.*t4.*t7.*2.0e2).*(1.0./2.0e2);
