function out1 = Compute_q2dd(I1,I2,T1,T2,g0,l1,lc1,lc2,m1,m2,q1,q2,q1d,q2d)
%COMPUTE_Q2DD
%    OUT1 = COMPUTE_Q2DD(I1,I2,T1,T2,G0,L1,LC1,LC2,M1,M2,Q1,Q2,Q1D,Q2D)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    02-Mar-2017 10:58:16

t2 = lc2.^2;
t3 = m2.*t2;
t4 = I2+t3;
t5 = 1.0./t4;
t7 = cos(q2);
t8 = l1.*lc2.*m2.*t7;
t6 = I2+t3+t8;
t9 = lc1.^2;
t10 = m1.*t9;
t11 = l1.^2;
t12 = t2+t11;
t13 = m2.*t12;
t14 = l1.*lc2.*m2.*t7.*2.0;
t15 = I1+I2+t10+t13+t14;
t16 = 1.0./t15;
t17 = q1+q2;
t18 = cos(t17);
t19 = sin(q2);
out1 = (t5.*(-T2+t6.*t16.*(T1-g0.*(cos(q1).*(l1.*m2+lc1.*m1)+lc2.*m2.*t18)+l1.*lc2.*m2.*t19.*(q1d.*q2d.*2.0+q2d.^2))+g0.*lc2.*m2.*t18+l1.*lc2.*m2.*q1d.^2.*t19))./(t5.*t6.^2.*t16-1.0);
