function eqn2 = ComputeAccel2(q1,q2,q1d,q2d)
%COMPUTEACCEL2
%    EQN2 = COMPUTEACCEL2(Q1,Q2,Q1D,Q2D)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    01-Mar-2017 17:17:49

t2 = q2.*2.0;
t3 = sin(q2);
t4 = q1d.^2;
t5 = q2d.^2;
t6 = sin(t2);
eqn2 = (cos(q1-q2).*-1.4715e4+cos(q1+q2).*1.3734e4+cos(q1+t2).*4.905e3-cos(q1).*6.867e4+t3.*t4.*5.4e3+t3.*t5.*2.5e3+t4.*t6.*1.0e3+t5.*t6.*5.0e2+q1d.*q2d.*t3.*5.0e3+q1d.*q2d.*t6.*1.0e3)./(cos(t2).*5.0e2-6.75e3);
