function E = ComputeEnergy(I1,I2,d1,d2,g0,l1,m1,m2,q1,q2,q1d,q2d)
%COMPUTEENERGY
%    E = COMPUTEENERGY(I1,I2,D1,D2,G0,L1,M1,M2,Q1,Q2,Q1D,Q2D)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    28-Feb-2017 12:33:40

t3 = q1+q2;
t4 = q1d+q2d;
t7 = cos(q1);
t2 = d2.*t4.*cos(t3)+l1.*q1d.*t7;
t9 = sin(q1);
t10 = sin(t3);
t5 = d2.*t4.*t10+l1.*q1d.*t9;
t6 = q1d.^2;
t8 = d1.^2;
E = I1.*t6.*(1.0./2.0)+m1.*(t6.*t7.^2.*t8+t6.*t8.*t9.^2).*(1.0./2.0)+I2.*t4.^2.*(1.0./2.0)+m2.*(t2.^2+t5.^2).*(1.0./2.0)+g0.*m2.*(d2.*t10+l1.*t9)+d1.*g0.*m1.*t9;
