function Q1DD = ComputeAccel1(T,q1,q2,q1d)
%COMPUTEACCEL1
%    Q1DD = COMPUTEACCEL1(T,Q1,Q2,Q1D)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    28-Feb-2017 13:29:59

Q1DD = (T.*5.0-cos(q1+q2).*(9.81e2./5.0e1)-q1d.^2.*sin(q2).*2.0)./(cos(q2).*2.0+5.0);
