function out1 = Compute_q1dd(I1,I2,T1,T2,g0,l1,lc1,lc2,m1,m2,q1,q2,q1d,q2d)
%COMPUTE_Q1DD
%    OUT1 = COMPUTE_Q1DD(I1,I2,T1,T2,G0,L1,LC1,LC2,M1,M2,Q1,Q2,Q1D,Q2D)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    02-Mar-2017 10:58:16

t2 = lc2.^2;
t3 = m2.*t2;
t5 = cos(q2);
t10 = l1.*lc2.*m2.*t5;
t4 = I2+t3+t10;
t6 = I2+t3;
t7 = 1.0./t6;
t8 = q1+q2;
t9 = cos(t8);
t11 = sin(q2);
t12 = lc1.^2;
t13 = m1.*t12;
t14 = l1.^2;
t15 = t2+t14;
t16 = m2.*t15;
t17 = l1.*lc2.*m2.*t5.*2.0;
t18 = I1+I2+t13+t16+t17;
t19 = 1.0./t18;
out1 = -(t19.*(T1-g0.*(cos(q1).*(l1.*m2+lc1.*m1)+lc2.*m2.*t9)+t4.*t7.*(-T2+g0.*lc2.*m2.*t9+l1.*lc2.*m2.*q1d.^2.*t11)+l1.*lc2.*m2.*t11.*(q1d.*q2d.*2.0+q2d.^2)))./(t4.^2.*t7.*t19-1.0);
