function Tc1 = TorqueNonColloacted(I1,I2,g0,kd1,kp1,l1,lc1,lc2,m1,m2,q1,q2,q1d,q2d,q1des)
%TORQUENONCOLLOACTED
%    TC1 = TORQUENONCOLLOACTED(I1,I2,G0,KD1,KP1,L1,LC1,LC2,M1,M2,Q1,Q2,Q1D,Q2D,Q1DES)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    14-Mar-2017 15:54:28

t2 = lc2.^2;
t3 = m2.*t2;
t4 = cos(q2);
t5 = l1.*lc2.*m2.*t4;
t6 = I2+t3;
t7 = 1.0./t6;
t8 = q1+q2;
t9 = cos(t8);
t10 = I2+t3+t5;
t11 = sin(q2);
Tc1 = -(kd1.*q1d+kp1.*(q1-q1des)).*(I2+t3+t5-t7.*t10.*(I1+I2+m2.*(t2+l1.^2)+lc1.^2.*m1+l1.*lc2.*m2.*t4.*2.0))+g0.*lc2.*m2.*t9-g0.*t7.*t10.*(cos(q1).*(l1.*m2+lc1.*m1)+lc2.*m2.*t9)+l1.*lc2.*m2.*q1d.^2.*t11+l1.*lc2.*m2.*t7.*t10.*t11.*(q1d.*q2d.*2.0+q2d.^2);
